<?php $id = $this->getRequest()->getParam('id'); ?>
<?php  if( isset($id) && is_numeric($id)   ): ?>
	<?php $item = $this->_getModel()->load($id)->getData(); ?>
	<?php if(empty($item)): ?>
	<?php
		Mage::app()
			->getFrontController()
			->getResponse()
			->setRedirect(
				$this->getUrl("blog/post/")
			);
	?>
	<?php endif; ?>
	<div class="inkatia-latests">
		<?php if($item['status']==1): ?>
		<div class="inkatia-post-item">
			<div class="inkatia-post-title">
				<h1><?php echo $item['title']; ?></h1>
			</div>
			<?php if(!empty($item['featured_image'])): ?>
				<div class="inkatia-featured-image">
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$item['featured_image']; ?>" alt="" title="" />
				</div>
			<?php endif; ?>
			<div class="inkatia-post-info">
				<?php echo $item['content_tinymce'];?>
			</div>
			<div class="inkatia-post-comments"></div>
		</div>
		<?php endif; ?>
	</div>
<?php else: ?>
	<?php 
		$collection = $this->_getCollection(); 
		$collection->getSelect("*")->order("inkatia_blog_id DESC")->limit("5");
		$data		= $collection->getData(); 
		$featured_image_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$item['featured_image'];
	?>
	<div class="inkatia-latests">
		<?php foreach($data as $item ): ?>
			<?php if($item['status']==1): ?>
			<div class="inkatia-post-item">
				<div class="inkatia-post-title">
					<h1><?php echo $item['title']; ?></h1>
				</div>
				<?php if(!empty($item['featured_image'])): ?>
				<div class="inkatia-post-left">
					<div class="inkatia-featured-image">
						<img width="100%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$item['featured_image']; ?>" alt="" title="" />
					</div>
				</div>
				<div class="inkatia-post-content">
					<div class="inkatia-post-info">
						<?php $text = Mage::helper('blog')->_parceTinyMceText( $item['content_tinymce'], $item['inkatia_blog_id'] ); ?>
						<?php echo $text; ?> - published: <?php $date = explode(" ",$item['created_time']); echo $date[0]; ?>
					</div>
				</div>
				<?php else: ?>
					<div class="inkatia-post-info">
						<?php $text = Mage::helper('blog')->_parceTinyMceText( $item['content_tinymce'], $item['inkatia_blog_id'] ); ?>
						<?php echo $text; ?> - published: <?php $date = explode(" ",$item['created_time']); echo $date[0]; ?>
					</div>
				<?php endif; ?>
				<div class="inkatia-post-comments"></div>
				<div class="div_clear"></div>
			</div>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
<?php endif; ?>



